version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive
    - gocritic
    - misspell

formatters:
  enable:
    - gofmt

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: empty-lines
      - name: error-strings
      - name: early-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: var-declaration
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
